# Generated by Django 2.1.7 on 2019-02-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nix_app', '0002_auto_20190227_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='creation_date',
            field=models.DateField(verbose_name='Data de criação'),
        ),
    ]
