# Generated by Django 2.1.7 on 2019-02-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nix_app', '0003_auto_20190227_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='nix_app.User', verbose_name='Transferências'),
        ),
    ]
